[project]
name = "webreinvent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai[tools]>=0.152.0",
    "fastapi[standard]>=0.116.1",
    "pydantic>=2.11.7",
]
